### ISSUE TITLE
IPC::Run does not play nice with FCGI

### ISSUE THREAD

**Issue by zts** [broquaint/Gitalist#9]
<t0m> The issue is IPC::Run ends up getting hold of the FCGI socket (somehow) and calling FILENO on it.
<t0m> now I have no idea how that works, given IPC::Run should be setting up pipes for stdout/stderr/stdin, forking and pushing stuff back and forth
@t0m it's quite possibly doing something like assuming STDERR is there so that it can dup/replace it or similar.. And the FCGI stuff is possibly doing something dumb like closing STDERR, then opening the FCGI socket (and so that getting fd2)..

The fail can be caused by starting gitalist_fastcgi.pl and navigating to the index page, which dies with this:
Caught exception in Gitalist::Controller::Root->auto "Can't locate object method "FILENO" via package "FCGI::Stream" at /Users/zts/perl5/lib/perl5/IPC/Run.pm line 1113.
Can't locate object method "FILENO" via package "FCGI::Stream" at /Users/zts/perl5/lib/perl5/IPC/Run.pm line 1113.
Can't locate object method "FILENO" via package "FCGI::Stream" at /Users/zts/perl5/lib/perl5/IPC/Run.pm line 1113.

However, if gitalist_fastcgi.pl is started with the -e option, things work again.

**Comment by bobtfish** [comment]
This is fixed by 75f6106 in http://github.com/bobtfish/Gitalist/commit/75f6106d28decbec4ccc29a39e460f3ecb7a5639

This however depends on a released version of Catalyst with http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Runtime/5.80/branches/better_scripts/

Which is significantly more likely than patched FCGI.pm ;)
